### ISSUE TITLE
readonly file system issue

### ISSUE THREAD

**Issue by debianmaster** [paulbrown/docker-zookeeper#1]
I'm getting this error, i have sufficient PVS and verified pv's are workign with another example.

``` sh
Zookeeper PEERS:
/onStart.sh: line 24: /opt/zookeeper/conf/zoo.cfg.dynamic: Read-only file system
Zookeeper MEMBERS: server.0=localhost:2888:3888:participant;2181
/usr/bin/java
Force enabled, data/txnlog directories will be re-initialized
Using myid of 2
/usr/bin/java
ZooKeeper JMX enabled by default
Using config: /opt/zookeeper/conf/zoo.cfg
mkdir: cannot create directory '/opt/zookeeper/bin/../logs': Read-only file system
/opt/zookeeper/bin/zkServer.sh: line 149: /opt/zookeeper/bin/../logs/zookeeper--server-zookeeper-2.out: No such file or directory
Starting zookeeper ... FAILED TO START
/usr/bin/java
Connecting to localhost:2181
2016-10-29 20:30:29,649 [myid:] - INFO  [main:Environment@109] - Client environment:zookeeper.version=3.5.2-alpha-1750793, built on 06/30/2016 13:15 GMT
2016-10-29 20:30:29,652 [myid:] - INFO  [main:Environment@109] - Client environment:host.name=zookeeper-2.zookeeper.test3.svc.cluster.local
2016-10-29 20:30:29,653 [myid:] - INFO  [main:Environment@109] - Client environment:java.version=1.8.0_101
2016-10-29 20:30:29,655 [myid:] - INFO  [main:Environment@109] - Client environment:java.vendor=Oracle Corporation
2016-10-29 20:30:29,655 [myid:] - INFO  [main:Environment@109] - Client environment:java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el7_2.x86_64/jre
2016-10-29 20:30:29,655 [myid:] - INFO  [main:Environment@109] - Client environment:java.class.path=/opt/zookeeper/bin/../build/classes:/opt/zookeeper/bin/../build/lib/*.jar:/opt/zookeeper/bin/../lib/slf4j-log4j12-1.7.5.jar:/opt/zookeeper/bin/../lib/slf4j-api-1.7.5.jar:/opt/zookeeper/bin/../lib/servlet-api-2.5-20081211.jar:/opt/zookeeper/bin/../lib/netty-3.10.5.Final.jar:/opt/zookeeper/bin/../lib/log4j-1.2.17.jar:/opt/zookeeper/bin/../lib/jline-2.11.jar:/opt/zookeeper/bin/../lib/jetty-util-6.1.26.jar:/opt/zookeeper/bin/../lib/jetty-6.1.26.jar:/opt/zookeeper/bin/../lib/javacc.jar:/opt/zookeeper/bin/../lib/jackson-mapper-asl-1.9.11.jar:/opt/zookeeper/bin/../lib/jackson-core-asl-1.9.11.jar:/opt/zookeeper/bin/../lib/commons-cli-1.2.jar:/opt/zookeeper/bin/../zookeeper-3.5.2-alpha.jar:/opt/zookeeper/bin/../src/java/lib/*.jar:/opt/zookeeper/bin/../conf:
2016-10-29 20:30:29,655 [myid:] - INFO  [main:Environment@109] - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2016-10-29 20:30:29,656 [myid:] - INFO  [main:Environment@109] - Client environment:java.io.tmpdir=/tmp
2016-10-29 20:30:29,656 [myid:] - INFO  [main:Environment@109] - Client environment:java.compiler=<NA>
2016-10-29 20:30:29,656 [myid:] - INFO  [main:Environment@109] - Client environment:os.name=Linux
2016-10-29 20:30:29,656 [myid:] - INFO  [main:Environment@109] - Client environment:os.arch=amd64
2016-10-29 20:30:29,656 [myid:] - INFO  [main:Environment@109] - Client environment:os.version=3.10.0-327.el7.x86_64
2016-10-29 20:30:29,656 [myid:] - INFO  [main:Environment@109] - Client environment:user.name=root
2016-10-29 20:30:29,656 [myid:] - INFO  [main:Environment@109] - Client environment:user.home=/root
2016-10-29 20:30:29,656 [myid:] - INFO  [main:Environment@109] - Client environment:user.dir=/
2016-10-29 20:30:29,656 [myid:] - INFO  [main:Environment@109] - Client environment:os.memory.free=110MB
2016-10-29 20:30:29,658 [myid:] - INFO  [main:Environment@109] - Client environment:os.memory.max=228MB
2016-10-29 20:30:29,658 [myid:] - INFO  [main:Environment@109] - Client environment:os.memory.total=115MB
2016-10-29 20:30:29,661 [myid:] - INFO  [main:ZooKeeper@855] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@51521cc1
2016-10-29 20:30:29,688 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1113] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2016-10-29 20:30:29,764 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1235] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:357)
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1214)
2016-10-29 20:30:29,869 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1113] - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
2016-10-29 20:30:29,871 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1235] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:357)
    at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1214)
KeeperErrorCode = ConnectionLoss for 
/usr/bin/java
ZooKeeper JMX enabled by default
Using config: /opt/zookeeper/bin/../conf/zoo.cfg
mkdir: cannot create directory '/opt/zookeeper/bin/../logs': Read-only file system
/opt/zookeeper/bin/zkServer.sh: line 196: kill: (49) - No such process
Stopping zookeeper ... STOPPED
/usr/bin/java
ZooKeeper JMX enabled by default
Using config: /opt/zookeeper/conf/zoo.cfg
mkdir: cannot create directory '/opt/zookeeper/bin/../logs': Read-only file system
2016-10-29 20:30:30,153 [myid:] - INFO  [main:QuorumPeerConfig@116] - Reading configuration from: /opt/zookeeper/conf/zoo.cfg
2016-10-29 20:30:30,156 [myid:] - INFO  [main:QuorumPeerConfig@308] - clientPort is not set
2016-10-29 20:30:30,156 [myid:] - INFO  [main:QuorumPeerConfig@322] - secureClientPort is not set
Invalid config, exiting abnormally
2016-10-29 20:30:30,157 [myid:] - ERROR [main:QuorumPeerMain@86] - Invalid config, exiting abnormally
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /opt/zookeeper/conf/zoo.cfg.dynamic
    at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:162)
    at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:110)
    at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:79)
Caused by: java.io.FileNotFoundException: /opt/zookeeper/conf/zoo.cfg.dynamic (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:143)
    ... 2 more
```

**Comment by kuang-byte** [comment]
@debianmaster Are you using Centos7 or the system with SElinux? If so, put securityContext inside yaml file.
   - name: zookeeper
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
