### ISSUE TITLE
Question: How to grant create file permission?

### ISSUE THREAD

**Issue by kuang-byte** [paulbrown/docker-zookeeper#3]
I am a beginner of k8s and would like to deploy cluster zookeeper. 
The Error I got is at below. 
```
Zookeeper PEERS:
Zookeeper MEMBERS: server.0=localhost:2888:3888:participant;2181
/usr/bin/java
Force enabled, data/txnlog directories will be re-initialized
mkdir: cannot create directory '/data/version-2': Permission denied
Using myid of 0
/opt/zookeeper/bin/zkServer-initialize.sh: line 112: /data/myid: Permission denied
/usr/bin/java
ZooKeeper JMX enabled by default
Using config: /opt/zookeeper/conf/zoo.cfg
/opt/zookeeper/bin/zkServer.sh: line 155: /data/zookeeper_server.pid: Permission denied
Starting zookeeper ... FAILED TO WRITE PID
/usr/bin/java
Connecting to localhost:2181
2017-02-13 15:03:11,809 [myid:] - INFO  [main:Environment@109] - Client environment:zookeeper.version=3.5.2-alpha-1750793, built on 06/30/2016 13:15 GMT
2017-02-13 15:03:11,865 [myid:] - INFO  [main:Environment@109] - Client environment:host.name=zookeeper-0.zookeeper.default.svc.cluster.local
2017-02-13 15:03:11,865 [myid:] - INFO  [main:Environment@109] - Client environment:java.version=1.8.0_101
2017-02-13 15:03:11,961 [myid:] - INFO  [main:Environment@109] - Client environment:java.vendor=Oracle Corporation
2017-02-13 15:03:11,961 [myid:] - INFO  [main:Environment@109] - Client environment:java.home=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.el7_2.x86_64/jre
2017-02-13 15:03:11,961 [myid:] - INFO  [main:Environment@109] - Client environment:java.class.path=/opt/zookeeper/bin/../build/classes:/opt/zookeeper/bin/../build/lib/*.jar:/opt/zookeeper/bin/../lib/slf4j-log4j12-1.7.5.jar:/opt/zookeeper/bin/../lib/slf4j-api-1.7.5.jar:/opt/zookeeper/bin/../lib/servlet-api-2.5-20081211.jar:/opt/zookeeper/bin/../lib/netty-3.10.5.Final.jar:/opt/zookeeper/bin/../lib/log4j-1.2.17.jar:/opt/zookeeper/bin/../lib/jline-2.11.jar:/opt/zookeeper/bin/../lib/jetty-util-6.1.26.jar:/opt/zookeeper/bin/../lib/jetty-6.1.26.jar:/opt/zookeeper/bin/../lib/javacc.jar:/opt/zookeeper/bin/../lib/jackson-mapper-asl-1.9.11.jar:/opt/zookeeper/bin/../lib/jackson-core-asl-1.9.11.jar:/opt/zookeeper/bin/../lib/commons-cli-1.2.jar:/opt/zookeeper/bin/../zookeeper-3.5.2-alpha.jar:/opt/zookeeper/bin/../src/java/lib/*.jar:/opt/zookeeper/bin/../conf:
2017-02-13 15:03:11,961 [myid:] - INFO  [main:Environment@109] - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2017-02-13 15:03:11,961 [myid:] - INFO  [main:Environment@109] - Client environment:java.io.tmpdir=/tmp
2017-02-13 15:03:11,962 [myid:] - INFO  [main:Environment@109] - Client environment:java.compiler=<NA>
2017-02-13 15:03:11,962 [myid:] - INFO  [main:Environment@109] - Client environment:os.name=Linux
2017-02-13 15:03:11,962 [myid:] - INFO  [main:Environment@109] - Client environment:os.arch=amd64
2017-02-13 15:03:11,962 [myid:] - INFO  [main:Environment@109] - Client environment:os.version=3.10.0-123.el7.x86_64
2017-02-13 15:03:11,962 [myid:] - INFO  [main:Environment@109] - Client environment:user.name=root
2017-02-13 15:03:11,962 [myid:] - INFO  [main:Environment@109] - Client environment:user.home=/root
2017-02-13 15:03:11,963 [myid:] - INFO  [main:Environment@109] - Client environment:user.dir=/
2017-02-13 15:03:11,964 [myid:] - INFO  [main:Environment@109] - Client environment:os.memory.free=227MB
2017-02-13 15:03:11,969 [myid:] - INFO  [main:Environment@109] - Client environment:os.memory.max=234MB
2017-02-13 15:03:11,969 [myid:] - INFO  [main:Environment@109] - Client environment:os.memory.total=234MB
2017-02-13 15:03:11,977 [myid:] - INFO  [main:ZooKeeper@855] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@51521cc1
2017-02-13 15:03:12,451 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1113] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2017-02-13 15:03:12,926 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1235] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:357)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1214)
2017-02-13 15:03:13,219 [myid:localhost:2181] - INFO  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1113] - Opening socket connection to server localhost/0:0:0:0:0:0:0:1:2181. Will not attempt to authenticate using SASL (unknown error)
2017-02-13 15:03:13,220 [myid:localhost:2181] - WARN  [main-SendThread(localhost:2181):ClientCnxn$SendThread@1235] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:357)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1214)
KeeperErrorCode = ConnectionLoss for 
/usr/bin/java
ZooKeeper JMX enabled by default
Using config: /opt/zookeeper/bin/../conf/zoo.cfg
Stopping zookeeper ... no zookeeper to stop (could not find file /data/zookeeper_server.pid)
/usr/bin/java
ZooKeeper JMX enabled by default
Using config: /opt/zookeeper/conf/zoo.cfg
2017-02-13 15:03:13,711 [myid:] - INFO  [main:QuorumPeerConfig@116] - Reading configuration from: /opt/zookeeper/conf/zoo.cfg
2017-02-13 15:03:13,718 [myid:] - INFO  [main:QuorumPeerConfig@308] - clientPort is not set
2017-02-13 15:03:13,718 [myid:] - INFO  [main:QuorumPeerConfig@322] - secureClientPort is not set
2017-02-13 15:03:13,727 [myid:] - WARN  [main:QuorumPeerConfig@581] - No server failure will be tolerated. You need at least 3 servers.
2017-02-13 15:03:13,729 [myid:] - ERROR [main:QuorumPeerMain@86] - Invalid config, exiting abnormally
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /opt/zookeeper/conf/zoo.cfg.dynamic
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:164)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:110)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:79)
Caused by: java.lang.IllegalArgumentException: myid file is missing
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.checkValidity(QuorumPeerConfig.java:663)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.setupQuorumPeerConfig(QuorumPeerConfig.java:534)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:159)
	... 2 more
Invalid config, exiting abnormally
```

**Comment by kuang-byte** [comment]
seems like it's seLinux problem is Centos 7.  Add securityContext in petset yml file solved the problem, but no sure if it's appropriate way.
